

class Autogenerated {
  ArrayOfSpecialityDt? arrayOfSpecialityDt;

  Autogenerated({this.arrayOfSpecialityDt});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    arrayOfSpecialityDt = json['ArrayOfSpeciality_dt'] != null
        ? new ArrayOfSpecialityDt.fromJson(json['ArrayOfSpeciality_dt'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.arrayOfSpecialityDt != null) {
      data['ArrayOfSpeciality_dt'] = this.arrayOfSpecialityDt!.toJson();
    }
    return data;
  }
}

class ArrayOfSpecialityDt {
  List<SpecialityDt>? specialityDt;

  ArrayOfSpecialityDt({this.specialityDt});

  ArrayOfSpecialityDt.fromJson(Map<String, dynamic> json) {
    if (json['Speciality_dt'] != null) {
      specialityDt = <SpecialityDt>[];
      json['Speciality_dt'].forEach((v) {
        specialityDt!.add(new SpecialityDt.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.specialityDt != null) {
      data['Speciality_dt'] =
          this.specialityDt!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class SpecialityDt {
  String? detail;
  int? spId;

  SpecialityDt({this.detail, this.spId});

  SpecialityDt.fromJson(Map<String, dynamic> json) {
    detail = json['detail'];
    spId = json['sp_id'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['detail'] = this.detail;
    data['sp_id'] = this.spId;
    return data;
  }
}

class filter_SpecialityDt {
  String? detail;
  int? sp_id;
  String? image;

  filter_SpecialityDt({this.detail, this.sp_id, this.image});

  filter_SpecialityDt.fromJson(Map<String, dynamic> json) {
    detail = json['detail'];
    sp_id = json['sp_id'];
    image = json['image'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['detail'] = this.detail;
    data['sp_id'] = this.sp_id;
    return data;
  }
}
