

class Autogenerated {
  ArrayOfRefererSetupGetDt? arrayOfRefererSetupGetDt;

  Autogenerated({this.arrayOfRefererSetupGetDt});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    arrayOfRefererSetupGetDt = json['ArrayOfRefererSetupGet_dt'] != null
        ? new ArrayOfRefererSetupGetDt.fromJson(
            json['ArrayOfRefererSetupGet_dt'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (arrayOfRefererSetupGetDt != null) {
      data['ArrayOfRefererSetupGet_dt'] = arrayOfRefererSetupGetDt!.toJson();
    }
    return data;
  }
}

class ArrayOfRefererSetupGetDt {
  List<RefererSetupGetDt>? refererSetupGetDt;

  ArrayOfRefererSetupGetDt({this.refererSetupGetDt});

  ArrayOfRefererSetupGetDt.fromJson(Map<String, dynamic> json) {
    if (json['RefererSetupGet_dt'] != null) {
      refererSetupGetDt = <RefererSetupGetDt>[];
      json['RefererSetupGet_dt'].forEach((v) {
        refererSetupGetDt!.add(new RefererSetupGetDt.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (refererSetupGetDt != null) {
      data['RefererSetupGet_dt'] =
          refererSetupGetDt!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

// class RefererSetupGetDt {
//   int? acCode;
//   String? address;
//   bool? appointment;
//   bool? consult;
//   String? consultTemplatename;
//   int? consultid;
//   String? detail;
//   bool? doctor;
//   String? email;
//   String? image;
//   String? intime;
//   int? min;
//   bool? oncall;
//   String? other;
//   String? outtime;
//   String? particular;
//   String? password;
//   bool? patho;
//   int? present;
//   String? professional;
//   String? publication;
//   String? qualification;
//   bool? radiologist;
//   int? rate;
//   String? referer;
//   int? refererType;
//   String? refererTypeDetail;
//   bool? refering;
//   int? refid;
//   int? regno;
//   String? salesman;
//   int? smCode;
//   int? spId;
//   int? specialized;
//   String? status;
//   int? telephone;
//   int? templateId;
//   int? templateid;
//   String? templatename;
//   String? zoomApikey;
//   String? zoomSecretkey;
//   String? zoomUser;

//   RefererSetupGetDt(
//       {this.acCode,
//       this.address,
//       this.appointment,
//       this.consult,
//       this.consultTemplatename,
//       this.consultid,
//       this.detail,
//       this.doctor,
//       this.email,
//       this.image,
//       this.intime,
//       this.min,
//       this.oncall,
//       this.other,
//       this.outtime,
//       this.particular,
//       this.password,
//       this.patho,
//       this.present,
//       this.professional,
//       this.publication,
//       this.qualification,
//       this.radiologist,
//       this.rate,
//       this.referer,
//       this.refererType,
//       this.refererTypeDetail,
//       this.refering,
//       this.refid,
//       this.regno,
//       this.salesman,
//       this.smCode,
//       this.spId,
//       this.specialized,
//       this.status,
//       this.telephone,
//       this.templateId,
//       this.templateid,
//       this.templatename,
//       this.zoomApikey,
//       this.zoomSecretkey,
//       this.zoomUser});

//   RefererSetupGetDt.fromJson(Map<String, dynamic> json) {
//     acCode = json['ac_code'];
//     address = json['address'];
//     appointment = json['appointment'];
//     consult = json['consult'];
//     consultTemplatename = json['consult_templatename'];
//     consultid = json['consultid'];
//     detail = json['detail'];
//     doctor = json['doctor'];
//     email = json['email'];
//     image = json['image'];
//     intime = json['intime'];
//     min = json['min'];
//     oncall = json['oncall'];
//     other = json['other'];
//     outtime = json['outtime'];
//     particular = json['particular'];
//     password = json['password'];
//     patho = json['patho'];
//     present = json['present'];
//     professional = json['professional'];
//     publication = json['publication'];
//     qualification = json['qualification'];
//     radiologist = json['radiologist'];
//     rate = json['rate'];
//     referer = json['referer'];
//     refererType = json['referer_type'];
//     refererTypeDetail = json['referer_type_detail'];
//     refering = json['refering'];
//     refid = json['refid'];
//     regno = json['regno'];
//     salesman = json['salesman'];
//     smCode = json['sm_code'];
//     spId = json['sp_id'];
//     specialized = json['specialized'];
//     status = json['status'];
//     telephone = json['telephone'];
//     templateId = json['template_id'];
//     templateid = json['templateid'];
//     templatename = json['templatename'];
//     zoomApikey = json['zoom_apikey'];
//     zoomSecretkey = json['zoom_secretkey'];
//     zoomUser = json['zoom_user'];
//   }

//   get name => null;

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['ac_code'] = this.acCode;
//     data['address'] = this.address;
//     data['appointment'] = this.appointment;
//     data['consult'] = this.consult;
//     data['consult_templatename'] = this.consultTemplatename;
//     data['consultid'] = this.consultid;
//     data['detail'] = this.detail;
//     data['doctor'] = this.doctor;
//     data['email'] = this.email;
//     data['image'] = this.image;
//     data['intime'] = this.intime;
//     data['min'] = this.min;
//     data['oncall'] = this.oncall;
//     data['other'] = this.other;
//     data['outtime'] = this.outtime;
//     data['particular'] = this.particular;
//     data['password'] = this.password;
//     data['patho'] = this.patho;
//     data['present'] = this.present;
//     data['professional'] = this.professional;
//     data['publication'] = this.publication;
//     data['qualification'] = this.qualification;
//     data['radiologist'] = this.radiologist;
//     data['rate'] = this.rate;
//     data['referer'] = this.referer;
//     data['referer_type'] = this.refererType;
//     data['referer_type_detail'] = this.refererTypeDetail;
//     data['refering'] = this.refering;
//     data['refid'] = this.refid;
//     data['regno'] = this.regno;
//     data['salesman'] = this.salesman;
//     data['sm_code'] = this.smCode;
//     data['sp_id'] = this.spId;
//     data['specialized'] = this.specialized;
//     data['status'] = this.status;
//     data['telephone'] = this.telephone;
//     data['template_id'] = this.templateId;
//     data['templateid'] = this.templateid;
//     data['templatename'] = this.templatename;
//     data['zoom_apikey'] = this.zoomApikey;
//     data['zoom_secretkey'] = this.zoomSecretkey;
//     data['zoom_user'] = this.zoomUser;
//     return data;
//   }
// }

class RefererSetupGetDt {
  String? referer;
  int? spId;
  int? refid;
  String? detail;
  String? email;
  String? qualification;

  RefererSetupGetDt({
    this.referer,
    this.spId,
    this.refid,
    this.detail,
    this.email,
    this.qualification,
  });

  RefererSetupGetDt.fromJson(Map<String, dynamic> json) {
    referer = json['referer'];
    spId = json['sp_id'];
    refid = json['refid'];
    detail = json['detail'];
    email = json['email'];
    qualification = json['qualification'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['referer'] = referer;
    data['sp_id'] = spId;
    data['refid'] = refid;
    data['email'] = email;
    data['qualification'] = qualification;
    return data;
  }

  get image => null;
}
